language: python

python:
    - "2.6"
    - "2.7"
    - "3.1"
    - "3.2"
    - "pypy"

before_install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip --quiet install argparse unittest2; fi
    - pip --quiet install coverage

install:
    - python setup.py --quiet install

script:
    - python test_docformatter.py
    - coverage run test_docformatter.py
    - coverage report --show-missing
