language: python

python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"

before_install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip --use-mirrors --quiet install argparse unittest2; fi

install:
    - python setup.py --quiet install

script:
    - python test_docformatter.py

after_success:
    - pip install --use-mirrors --quiet coverage
    - coverage run --include='docformatter.py,test_docformatter.py' test_docformatter.py
    - coverage report --show-missing

    - pip install --use-mirrors --quiet coveralls
    - coveralls
