language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "pypy"
before_install:
    - ./scripts/travis_conditional_dependencies.bash
    - pip --quiet install coverage
install:
    - python setup.py --quiet install
script:
    - python test_docformatter.py
    - coverage run test_docformatter.py
    - coverage report --show-missing
