language: python

python:
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"

env:
    -
    - LANG=

install:
    - python setup.py --quiet install

script:
    - python test_docformatter.py
    - docformatter setup.py

after_success:
    - pip install --quiet coverage
    - make coverage

    - pip install --quiet coveralls
    - coveralls
